### ISSUE TITLE
What is difference between this package and nuxt-storybook?

### ISSUE THREAD

**Issue by rlam3** [richardeschloss/nuxt-stories#58]
What is difference between this package and nuxt-storybook?

https://github.com/mstrlaw/nuxt-storybook

Thanks!

**Comment by richardeschloss** [comment]
Hi, great question! The UI is completely differnent and the approach is completely different to storybooking. I plan to write an article on this exact subject. nuxt-stories is a project I created when storybookjs couldn't quite meet my personal preferences, but storybookjs works for a world of people. 

Most likely, nuxt-storybook is using storybookjs under the hood, but that's now become absolute with Nuxt's newest release. I beleive Nuxt ships now with storybookjs in it (at @nuxt/storybook, I think. Advertised as "zero-config").

But, if you'd like to see a more detail explanation, it's here: https://nuxt-stories.netlify.app/stories/Documentation/Introduction

You can also try out the live editing / compilation at my demo and get an idea of what my goals are. The UI still has work ahead of it. Pretty soon I'll be shipping an important feature with it. 

Again, it comes down to personal preference.

**Comment by richardeschloss** [comment]
https://medium.com/javascript-in-plain-english/introduction-to-story-driven-development-with-nuxt-stories-5f2f160aaccb
