### ISSUE TITLE
Error building for the first time due to files names which have spaces

### ISSUE THREAD

**Issue by Saunved** [richardeschloss/nuxt-stories#84]
There are many files in the ```stories``` folder which have spaces in them. This causes issues when running ```yarn dev```. This is the error I got:
```
saunved@laptop:~/Sandbox/story-test$ yarn dev
yarn run v1.22.10
$ nuxt
ℹ Merging Tailwind config from ~/tailwind.config.js                                                      nuxt:tailwindcss 18:43:10
ℹ socket.io server listening on localhost:3001                                                                            18:43:11

 FATAL  ENOENT: no such file or directory, open '/home/saunved/Sandbox/story-test/stories/en/Documentation/Fetching%20Data.md'

  at Object.openSync (fs.js:462:3)
  at readFileSync (fs.js:364:35)
  at mapStory (node_modules/nuxt-stories/lib/module.register.js:270:26)
  at node_modules/nuxt-stories/lib/module.register.js:275:52
  at Array.map (<anonymous>)
  at mapStory (node_modules/nuxt-stories/lib/module.register.js:275:35)
  at node_modules/nuxt-stories/lib/module.register.js:284:28
  at Array.map (<anonymous>)
  at Object.stories (node_modules/nuxt-stories/lib/module.register.js:284:8)
  at Object.routes (node_modules/nuxt-stories/lib/module.register.js:222:34)

```

I got the same error for other files with spaces in them until I deleted all of them (mostly all Markdown files). I'm not sure what could be done about this, but I am guessing other people will come across this issue at some point too.

Thanks!

**Comment by richardeschloss** [comment]
I think you need to update nuxt-stories to the latest 2.0.14. This issue was fixed a while ago by replacing the HTML entities ("%20") in the URL with spaces to handle the filenames properly.  (Update nuxt, nuxt-stories, nuxt-socket-io)

**Comment by Saunved** [comment]
@richardeschloss My nuxt-stories module is actually at 2.0.14
If you want, I could publish a git repo for you to take a look at if I am able to reproduce this error

**Comment by richardeschloss** [comment]
I think it'd be best to fork this repo and create a branch showing the issue in the fork. Thanks for letting me know.

**Comment by richardeschloss** [comment]
Hmm, ok I can repro this too. I'll investigate.

**Comment by richardeschloss** [comment]
Fix is coming soon...

**Comment by richardeschloss** [comment]
2.0.15 released with the fix for this issue.
