### ISSUE TITLE
socket.io throws CORS error, have to use Chrome extension

### ISSUE THREAD

**Issue by Saunved** [richardeschloss/nuxt-stories#85]
I don't know if there's a way to avoid installing a Chrome extension for getting rid of CORS, but I think it's necessary to mention this in the README for people who might not be sure

I used this to get rid of CORS errors. My components were not visible until then
https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino/related?hl=en

**Comment by richardeschloss** [comment]
Most likely just need to update nuxt-socket-io to the latest stable, which updated its socket.io dep to v3 (and addressed a slew of CORS issues). We resolved that one about 1-2 months ago. Thread here: https://github.com/richardeschloss/nuxt-socket-io/issues/167
