### ISSUE TITLE
Can we use the existing components directory for a smoother workflow?

### ISSUE THREAD

**Issue by Saunved** [richardeschloss/nuxt-stories#86]
I know I am creating a lot of issues, but I am really excited about using this module and I think it's important to get some clarity on its usage, especially since it's relatively young.

Here's my question:
Can we utilize the existing ```components``` directory that exists in Nuxt for showing the components on the ```localhost:3000/stories/components``` page?

As per my understanding, the components that I create in the stories/en/components directory will be shown on the stories path, and the components I create in Nuxt will not actually be visible at all.

There could be a "watch" process that copies the components over into the /stories directory to take care of this issue, or maybe there's a smarter way through symbolic links (but I am not sure about this).

I really love how simple this module is making things and I appreciate the work you've done. Looking forward to your response!

**Comment by richardeschloss** [comment]
As mentioned in the [docs](https://nuxt-stories.netlify.app/stories/en/Documentation) any component that is in the `~/components` directory (and sub-directories) will be auto imported. 

To clarify...there's a key difference between components and stories that describe what the components do. The Nuxt approach would be to have the components in your `~/components` directory while `~/stories/en/components` would contain the stories (a.k.a. requirements) for those components. But it's really up to you how you organize the stories, whereas organizing the components the Nuxt way is a bit more strict.

For example, suppose you have a very simple component Counter.vue. The organization would probably be:

- `~/components/Counter.vue`: contains the Vue component counter
- `~/stories/en/Components/Counter.md`: contains information like, "The counter component shall increment count and be colored blue". And right there in that story you should be able to write `<Counter />` to test it out. 

I hope this helps.
